apiVersion: v1
kind: Secret
metadata:
  name: ib-kubernetes-ufm-secret
  namespace: nvidia-network-operator
type: Opaque
stringData:
  UFM_USERNAME: "placeholder"
  UFM_PASSWORD: "placeholder"
  UFM_ADDRESS: "127.0.0.1"
  UFM_HTTP_SCHEMA: "http"
  UFM_PORT: "80"
  UFM_CERTIFICATE: ""
