apiVersion: v1
kind: Namespace
metadata:
  name: seaweed-vfs-poc
---
apiVersion: v1
kind: Pod
metadata:
  name: seaweed-vfs-client
  namespace: seaweed-vfs-poc
  labels:
    app.kubernetes.io/name: seaweed-vfs-client
    app.kubernetes.io/part-of: seaweed-vfs-poc
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: hnode4
  tolerations:
    - operator: Exists
  containers:
    - name: shell
      image: ubuntu:24.04
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - -lc
      args:
        - sleep infinity
      volumeMounts:
        - name: seaweed-vfs
          mountPath: /mnt/seaweedvfs
          mountPropagation: HostToContainer
  volumes:
    - name: seaweed-vfs
      hostPath:
        path: /var/lib/seaweedfs-vfs/mnt
        type: DirectoryOrCreate
